@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam activity {
    BackgroundColor White
    DiamondBackgroundColor #FDF6E3
    DiamondBorderColor #B58900
}

start

:User inputs "addbasic n/Jadon p/88880000";
:Parse command;

if (Are prefixes valid?) then (no)
    :Display "Invalid command format: only n/ and p/ are allowed";
    stop
else (yes)
    if (Are required fields missing?) then (yes)
        :Display "Missing required field(s): name or phone";
        stop
    else (no)
        if (Are argument values valid?) then (no)
            :Display "Invalid field value(s): check name or phone";
            stop
        else (yes)
            if (Contact already exists?) then (yes)
                :Display "This person already exists in the contact book";
                stop
            else (no)
                :Add new person to Model;
                :Save updated AddressBook to Storage;
                :Display "You have successfully added the contact";
            endif
        endif
    endif
endif

stop
@enduml
