@startuml
start
:User enters command filter;
:Parse command arguments;
if () then ([All inputs are valid])
  :Generate new FilterCommand;
  :Display filtered list;
  :Generate success message;
else ([else])
  :Generate error message;
endif
:Display result message to user;
stop
@enduml
